export default {
    USER_LEAVES_ROOM:   'USER_LEAVES_ROOM',
    USER_JOINS_ROOM:    'USER_JOINS_ROOM',
    CHAT_MESSAGE:       'CHAT_MESSAGE',
    INPUT_CHANGED:      'INPUT_CHANGED',
    INPUT_SUBMITTED:    'INPUT_SUBMITTED',
    LOGOUT:             'LOGOUT'
}
